[ids]
*

[main]
leftmeta = layer(meta_mac)
leftcontrol = layer(ctrl_layer)

[meta_mac:C]
c = C-insert # c = C-S-c
v = S-insert # v = C-S-v 
x = S-delete
z = C-z
S-z = C-S-z

left = home
right = end
up = C-home
down = C-end

# hyprland設定側でalt spaceでquickshell起動
# qmk側でlayer + EnterをSpaceにしている
space = A-space

[ctrl_layer:C]
backspace = esc
